default:
  before_script:
    - docker info

build-api:
  stage: build
  script:
    - cd api
    - echo $DOCKER_PASSWORD | docker login --username ydewilde --password-stdin
    - docker build . -t ydewilde/doodleapi

build-front:
  stage: build
  script:
    - cd front
    - echo $DOCKER_PASSWORD | docker login --username ydewilde --password-stdin
    - docker build . -t ydewilde/doodlefront 

# deploy-prod:
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#   environment: production