default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

variables:
  DOCKER_TLS_CERTDIR: ""

build-api:
  stage: build
  script:
    - cd api
    - echo $DOCKER_PASSWORD | docker login --username ydewilde --password-stdin
    - docker build . -t ydewilde/doodleapi
    - docker image push ydewilde/doodleapi

build-front:
  stage: build
  script:
    - cd front
    - echo $DOCKER_PASSWORD | docker login --username ydewilde --password-stdin
    - docker build . -t ydewilde/doodlefront 
    - docker image push ydewilde/doodlefront

deploy-prod:
  stage: deploy
  script:
    - ssh -i $PRIVATE_KEY zprojet@ydew.istic.univ-rennes1.fr "rm -rf ~/doodle && mkdir ~/doodle"
    - scp -i $PRIVATE_KEY -r nginx zprojet@ydew.istic.univ-rennes1.fr:~/doodle
    - scp -i $PRIVATE_KEY docker-compose.yaml zprojet@ydew.istic.univ-rennes1.fr:~/doodle
    - scp -i $PRIVATE_KEY api/APIKEY.txt zprojet@ydew.istic.univ-rennes1.fr:~/doodle
    # - ssh -i $PRIVATE_KEY zprojet@ydew.istic.univ-rennes1.fr "cd ~/doodle && docker compose up" 
  environment: production