version: "3.8"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 2
  etherpad:
    image: etherpad/etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
    healthcheck:
      test: "wget 0.0.0.0:9001/health --spider -q"
      interval: 10s
      timeout: 10s
      retries: 2
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  api:
    image: iziny/doodleapi
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: "wget 0.0.0.0:8080 --spider -q"
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      db:
        condition: service_healthy
      etherpad:
        condition: service_healthy
    links:
      - db
      - etherpad
  myadmin:
    image: phpmyadmin:latest
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    image: iziny/doodlefront
    ports:
      - "4200:80"
    depends_on:
      api:
        condition: service_healthy
